### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by kporras07** [ManatiCR/manatime#14]
As an administrator
I want to create and edit tasks
- Tasks should have a billable/non-billable field.

**Comment by kporras07** [comment]
DoD:
- As an administrator I should be able to go to node/add/task and add a new task with the described fields
- As an administrator, I should be able to view a task (no themed) and click on the Edit tab and update that task.

**Comment by cienvaras** [comment]
Fields:
- Name (title)
- Description (text)
- Project (entity reference with Inline Entity Form)
- Billable (boolean)
