### ISSUE TITLE
Projects Listing

### ISSUE THREAD

**Issue by cienvaras** [ManatiCR/manatime#22]
As an administrator
I want to see a projects listing and have options associated to each (or all) projects.

**Comment by kporras07** [comment]
DoD:
- As an administrator I want to go /projects and get a table with a list of Project Name, Client Names.
- In that view, I need to have direct links to edit projects

I need to have 2 views (/projects/active and /projects/inactive and by default /projects go to /projects/active)

This view should use a custom permission
