### ISSUE TITLE
Tasks Listing

### ISSUE THREAD

**Issue by kporras07** [ManatiCR/manatime#24]
As an administrator
I want to see a list of all tasks associated with a specific project

**Comment by kporras07** [comment]
DoD:
- Go to a project
- It should have a content pane view that lists all associated tasks (display should use panels)

**Comment by robherba** [comment]
which fields you like to see?

**Comment by robherba** [comment]
@kporras07

**Comment by kporras07** [comment]
As in other listings; as table:
- Name
- Billable

Project is not necessary because we're seeing the project.

Thanks for asking.

**Comment by robherba** [comment]
Ok, thank you!
